### ISSUE TITLE
getting False everytime, even when data is from Telegram.

### ISSUE THREAD

**Issue by ghost** [alxpy/python-telegram-auth#1]
Sorry to say, But I'm getting `False`  everytime, even when I log with [Telegram-Auth-Widget.](https://core.telegram.org/widgets/login#receiving-authorization-data)
My code snippets are :- 

[Flask app.](https://del.dog/ylofixaili.py)
[My bot script](https://del.dog/mimecucrec.py)

I'm passing a `dict` of received data to `verify_auth_data(..., ...)` 
Example of [received data.](https://del.dog/pimithonux.json) how I pass to the module. Hope, the data is correct.

Thanks in advance.

**Comment by ghost** [comment]
Welll, It works. But what if the data is blank ?
like there is no profile photo ?
that should be poped ? or have `None` or `""` ?

**Comment by mr-st0rm** [comment]
can u solve it?
